name: Mailit Deployment 

on:
  push:
    branches:
      - master

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo 
      - uses: actions/checkout@v4 

      - name: cd into backend_dir
      - run: cd ./backend 

      - name: install depencies 
      - run: npm i 

      - name: run test 
      - run: echo "Running test..."  

