name: Mailit Deployment 

on:
  push:
    branches:
      - master

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo 
        uses: actions/checkout@v4  

      - name: install depencies 
        run: npm i -w backend

      - name: run test 
        run: echo "Running test..."  

