name: Mailit Deployment 

on:
  push:
    branches:
      - master

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - run: echo "Checking"
      - run: npm i 
      - run: echo "Running test..."  

